version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "output-topic:1:1"
  jobmanager:
    image: ${FLINK_IMAGE_NAME:-flink}
    expose:
      -  "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - "27017:27017"
  app:
    image: kafka-flink-mongo
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
      - mongodb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FLINK_JOB_MANAGER_HEAP_SIZE: 1g
      MONGO_URI: mongodb://mongodb:27017/patient-db
      MONGO_DB: patient-db